version: '3.9'

services:
  nestjs:
    build:
      context: /
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9228:9229
    volumes:
      - ./:/usr/src/app
      - nestjs_node_modules_data:/usr/src/app/node_modules
      - nestjs_dist_data:/usr/src/app/dist
    command: bash -c "yarn; yarn start:debug"
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      JWT_SECRET: secret
      ADMIN_PASSWORD: Compl3xP@ssw0rd!

  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db_data:
  nestjs_node_modules_data:
  nestjs_dist_data:
